#################################################################
##### Initializing the Cluster                              #####
#################################################################
- name: STARTING CLUSTER K8S
  hosts: control_plane_master
  vars_files: "/storage/automation/ansible-files/kban-variables.yaml"
  tasks:
  - name: Loading variables
    ansible.builtin.include_vars:
      dir: "/"
      files_matching: kban-variables.yaml
  - name: Clean Previous Installations
    command: kubeadm reset -f
  - name: Start Cluster with Kubeadm
    command: kubeadm init --apiserver-advertise-address={{ ip_master }} --control-plane-endpoint "{{ cp_endpoint }}:6443" \ --upload-certs --pod-network-cidr={{ pod_cidr }} --service-cidr={{ svc_cidr }}
  - name: Create directory .kube
    file:
      path: ~/.kube
      state: directory
      owner: root
      group: root
      mode: '644'
  - name: Copy config file
    copy:
      dest: ~/.kube/config
      src: /etc/kubernetes/admin.conf
      remote_src: yes
      owner: root
      group: root
      mode: '640'
  - name: Install Calico
    command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml
    # command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  - name: Generate Join ControlPlane/Worker Command
    shell: kubeadm token create --print-join-command
    register: print_join_command
  - name: Add Command Join in set_fact
    set_fact: join_command="{{ print_join_command.stdout }}"
  - name: Generate Key for Join Others Control Planes
    shell: kubeadm init phase upload-certs --upload-certs

################################################################
#### Initializing the Workers                              #####
################################################################
- name: STARTING JOIN KUBERNETES WORKERS
  hosts: worker_node
  tasks:
  - name: Clean Previous Installations in Workers
    command: kubeadm reset -f
  - name: Executing Join Command in Workers
    command: "{{ hostvars[groups['control_plane'][0]]['join_command'] }}"
