################################################################
#### Initializing the New ControlPlane                     #####
################################################################
- name: COPY/EXECUTION JOIN COMMAND CONTROLPLANE
  hosts: control_plane_backup
  tasks:
  - name: Clean Previous Installations in ControlPlane
    command: kubeadm reset -f
  - name: COPY Script - Copy Join Command ( --->>> )
    ansible.builtin.copy:
      src: /storage/automation/scripts/controlplanejoin.sh
      dest: /tmp/controlplanejoin.sh
      mode: '777'
  - name: EXECUTE Script - Copy Join Command
    shell: "/tmp/controlplanejoin.sh"
