apiVersion: v1
kind: Namespace
metadata:
  name: labpostgres

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: sysadmin
  POSTGRES_PASSWORD: 1q2w3e4r

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: c3lzYWRtaW4K
  POSTGRES_PASSWORD: MXEydzNlNHIK

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.7
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - mountPath: /var/lib/pgsql/14/data/
          name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: database-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: labpostgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30100
  type: NodePort

