apiVersion: v1
kind: Namespace
metadata:
  name: mongo

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: mongo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0.5
        ports:
        - containerPort: 27017
        livenessProbe:
          httpGet:
            path: /
            port: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin
        volumeMounts:
        - mountPath: "/data/db"
          name: mongodb-static
      volumes:
      - name: mongodb-static
        persistentVolumeClaim:
          claimName: mongodb-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongo
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32000
  type: NodePort
