apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: metallb-config
data:
  config: |
    address-pools:
    - name: pool-ip
      protocol: layer2
      addresses:
      - 192.168.99.210-192.168.99.230

---

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-ip
  namespace: default
spec:
  addresses:
  - 192.168.99.210-192.168.99.230

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: acme-pool-ip
  namespace: default
spec:
  ipAddressPools:
  - pool-ip

