apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: labpostgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.7
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/pgsql/14/data/
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: database-pvc
