apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: labpostgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30100
  type: NodePort

