apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: labpostgres
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: sysadmin
  POSTGRES_PASSWORD: 1q2w3e4r
